# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0de5c8ef15501ae9627d308bb5c9d6678f775efc865a7288007d391ea9edbab515756a9d9abb20a16776402841d6986e85b8c56d11e011024060bca49d4c8f4a

test:
  secret_key_base: 3e133ccc98a8bcf25977b6d8ebad09424017d989ba51d1e317f1a4c1e092261ddc9ed39b80512239e6c5b866a5c1a1ed7aa3b392e3d21a2cd29486c67580f7d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
